import { getProjectRoot, compose } from "../lib/compose.ts";
import { ensureEnvFile, setEnvVar } from "../lib/env.ts";
import { ensureKeyPair, pubKeyPath, injectSshConfig } from "../lib/ssh.ts";
import { Input, Confirm } from "../lib/prompt.ts";
import { resolve } from "@std/path";
import { bold, green, cyan, dim } from "@std/fmt/colors";

/** このプラットフォームでの ~/.claude のデフォルトパスを返す */
function defaultClaudeHome(): string {
  if (Deno.build.os === "windows") {
    return `${Deno.env.get("USERPROFILE")}\\.claude`;
  }
  return `${Deno.env.get("HOME")}/.claude`;
}

/** docker-compose.local.yml を生成する */
function generateLocalCompose(
  projectRoot: string,
  options: { claudeHome?: string; workspaceVolume?: boolean },
): void {
  const localPath = resolve(projectRoot, "docker-compose.local.yml");

  const volumes: string[] = [];
  if (options.claudeHome) {
    volumes.push("      - ${CLOOPY_CLAUDE_HOME}:/home/developer/.claude");
  }
  if (options.workspaceVolume) {
    volumes.push("      - workspace-data:/home/developer/workspace");
  }

  // オーバーライド不要 → 古いファイルがあれば削除
  if (volumes.length === 0) {
    try {
      Deno.removeSync(localPath);
      console.log(dim("[cloopy] docker-compose.local.yml を削除しました (オーバーライド不要)"));
    } catch { /* 存在しなかった */ }
    return;
  }

  let content = `# Auto-generated by cloopy setup
# Edit freely. This file is .gitignored.
services:
  sandbox:
    volumes:
${volumes.join("\n")}
`;
  if (options.workspaceVolume) {
    content += `
volumes:
  workspace-data:
`;
  }
  Deno.writeTextFileSync(localPath, content);
  console.log(green("[cloopy] docker-compose.local.yml を生成しました"));
}

export async function setup(): Promise<void> {
  const projectRoot = getProjectRoot();

  console.log("");
  console.log(bold(cyan("  cloopy セットアップ")));
  console.log("");

  // --------------------------------------------------------------------------
  // 1. SSH 鍵
  // --------------------------------------------------------------------------
  console.log(bold("--- ステップ 1: SSH 鍵 ---"));
  await ensureKeyPair();
  console.log("");

  // --------------------------------------------------------------------------
  // 2. .env 設定 (自動 + 対話)
  // --------------------------------------------------------------------------
  console.log(bold("--- ステップ 2: 環境設定 ---"));
  const envPath = ensureEnvFile(projectRoot);

  // 自動設定 (マーカーセクションに配置)
  setEnvVar(envPath, "CLOOPY_PUBKEY_PATH", pubKeyPath(), true);

  if (Deno.build.os !== "windows") {
    const uid = new Deno.Command("id", { args: ["-u"], stdout: "piped" });
    const gid = new Deno.Command("id", { args: ["-g"], stdout: "piped" });
    const [uidResult, gidResult] = await Promise.all([uid.output(), gid.output()]);
    const uidStr = new TextDecoder().decode(uidResult.stdout).trim();
    const gidStr = new TextDecoder().decode(gidResult.stdout).trim();
    setEnvVar(envPath, "CLOOPY_USER_UID", uidStr, true);
    setEnvVar(envPath, "CLOOPY_USER_GID", gidStr, true);
  }

  console.log("");

  // 対話設定
  const currentPort = Deno.env.get("CLOOPY_SSH_PORT") ?? "10022";
  const portInput = await Input.prompt({
    message: "SSH ポート",
    default: currentPort,
    validate: (v) => {
      const n = Number(v);
      if (!Number.isInteger(n) || n < 1 || n > 65535) {
        return "1〜65535 の整数を入力してください";
      }
      return true;
    },
  });
  if (portInput !== currentPort) setEnvVar(envPath, "CLOOPY_SSH_PORT", portInput);

  const currentTz = Deno.env.get("CLOOPY_TIMEZONE") ?? "Asia/Tokyo";
  const tzInput = await Input.prompt({ message: "タイムゾーン", default: currentTz });
  if (tzInput !== currentTz) setEnvVar(envPath, "CLOOPY_TIMEZONE", tzInput);

  const currentWs = Deno.env.get("CLOOPY_HOST_WORKSPACE") ?? "./workspace";
  const wsInput = await Input.prompt({ message: "ワークスペースパス", default: currentWs });
  if (wsInput !== currentWs) setEnvVar(envPath, "CLOOPY_HOST_WORKSPACE", wsInput);

  const useVolume = await Confirm.prompt({
    message: "ワークスペースに Docker ボリュームを使用しますか？ (Windows 推奨)",
    default: false,
  });
  setEnvVar(envPath, "CLOOPY_WORKSPACE_VOLUME", useVolume ? "true" : "false");

  console.log("");

  // --------------------------------------------------------------------------
  // 3. SSH 設定
  // --------------------------------------------------------------------------
  console.log(bold("--- ステップ 3: SSH 設定 ---"));
  injectSshConfig(portInput);
  console.log("");

  // --------------------------------------------------------------------------
  // 4. Claude 設定
  // --------------------------------------------------------------------------
  console.log(bold("--- ステップ 4: Claude 設定 ---"));
  let claudeHome: string | undefined;
  const mountClaude = await Confirm.prompt({
    message: "ホストの ~/.claude をコンテナにマウントしますか？",
    default: true,
  });
  if (mountClaude) {
    const defaultPath = defaultClaudeHome();
    claudeHome = await Input.prompt({ message: ".claude のパス", default: defaultPath });
    setEnvVar(envPath, "CLOOPY_CLAUDE_HOME", claudeHome);
  }

  // docker-compose.local.yml を生成
  generateLocalCompose(projectRoot, {
    claudeHome,
    workspaceVolume: useVolume,
  });
  console.log("");

  // --------------------------------------------------------------------------
  // 5. ビルド & 起動
  // --------------------------------------------------------------------------
  console.log(bold("--- ステップ 5: ビルド & 起動 ---"));
  console.log("[cloopy] イメージをビルド中...");
  let code = await compose(projectRoot, ["build"]);
  if (code !== 0) {
    console.error("[cloopy] エラー: ビルドに失敗しました");
    Deno.exit(1);
  }

  console.log("[cloopy] コンテナを起動中...");
  code = await compose(projectRoot, ["up", "-d", "--wait", "--wait-timeout", "300", "--remove-orphans"]);
  if (code !== 0) {
    console.error("[cloopy] エラー: コンテナの起動に失敗しました");
    Deno.exit(1);
  }
  console.log("");

  // --------------------------------------------------------------------------
  // 完了
  // --------------------------------------------------------------------------
  console.log(bold(green("  cloopy の準備ができました！")));
  console.log("");
  console.log(`  SSH:      ${cyan("ssh cloopy")}`);
  console.log(`  VS Code:  ${cyan("code --remote ssh-remote+cloopy /home/developer/workspace")}`);
  console.log("");
}
