import {
  checkBootstrapStatus,
  compose,
  getProjectRoot,
} from "../lib/compose.ts";
import { ensureEnvFile, readEnvFile, setEnvVar } from "../lib/env.ts";
import {
  authorizedKeysPath,
  loadKeyStore,
  rebuildAuthorizedKeys,
  type StoredKey,
} from "../lib/keys.ts";
import { loadRemoteStore } from "../lib/remote.ts";
import {
  ensureKeyPair,
  injectSshConfig,
  refreshKnownHosts,
} from "../lib/ssh.ts";
import { Confirm, Input } from "../lib/prompt.ts";
import {
  COMPOSE_UP_ARGS,
  DEFAULT_INSTANCE_NAME,
  DEFAULT_SSH_PORT,
  DEFAULT_TIMEZONE,
  DEFAULT_WORKSPACE,
  LOCAL_BIND,
} from "../lib/constants.ts";
import { resolve } from "@std/path";
import { validateWorkspacePath } from "../lib/workspace.ts";
import { bold, cyan, dim, green, yellow } from "@std/fmt/colors";

/** docker-compose.local.yml を生成する */
function generateLocalCompose(
  projectRoot: string,
  options: { workspaceVolume?: boolean },
): void {
  const localPath = resolve(projectRoot, "docker-compose.local.yml");

  const volumes: string[] = [];
  if (options.workspaceVolume) {
    volumes.push("      - workspace-data:/home/developer/workspace");
  }

  // オーバーライド不要 → 古いファイルがあれば削除
  if (volumes.length === 0) {
    try {
      Deno.removeSync(localPath);
      console.log(
        dim(
          "[cloopy] docker-compose.local.yml を削除しました (オーバーライド不要)",
        ),
      );
    } catch { /* 存在しなかった */ }
    return;
  }

  let content = `# Auto-generated by cloopy setup
# Edit freely. This file is .gitignored.
services:
  sandbox:
    volumes:
${volumes.join("\n")}
`;
  if (options.workspaceVolume) {
    content += `
volumes:
  workspace-data:
`;
  }
  Deno.writeTextFileSync(localPath, content);
  console.log(green("[cloopy] docker-compose.local.yml を生成しました"));
}

/**
 * イメージが未ビルドのとき専用: 対話なしでビルド＆起動する。
 * .env / SSH 設定は整備済みであることが前提。
 */
export async function buildAndStart(): Promise<void> {
  const projectRoot = getProjectRoot();
  const env = readEnvFile(projectRoot);
  const port = env.get("CLOOPY_SSH_PORT") ?? DEFAULT_SSH_PORT;

  console.log("");
  console.log(bold("--- コンテナを起動中 ---"));
  console.log("[cloopy] コンテナを起動中...");
  const code = await compose(projectRoot, [...COMPOSE_UP_ARGS]);
  if (code !== 0) {
    console.error("[cloopy] エラー: コンテナの起動に失敗しました");
    console.error(
      "[cloopy] 設定は保存済みです。上のログで原因を解消してから ./manage.sh を再実行してください",
    );
    Deno.exit(1);
  }
  await refreshKnownHosts(port);
  await checkBootstrapStatus(projectRoot);
  console.log("");
}

export async function setup(): Promise<void> {
  const projectRoot = getProjectRoot();

  // LAN 公開質問のデフォルト判定用: 既存 .env (= bind 未設定なら従来どおり
  // 全 IF 公開で使われてきた) か、新規 (= 安全側の localhost 限定を既定に) か
  let envExisted = true;
  try {
    Deno.statSync(resolve(projectRoot, ".env"));
  } catch {
    envExisted = false;
  }

  console.log("");
  console.log(bold(cyan("  cloopy セットアップ")));
  console.log("");

  // --------------------------------------------------------------------------
  // 1. SSH 鍵
  // --------------------------------------------------------------------------
  console.log(bold("--- ステップ 1: SSH 鍵 ---"));
  await ensureKeyPair();

  // コンテナへ渡す authorized_keys 束ファイル（自動生成鍵 + keys.json の
  // 追加鍵）を再生成する。追加鍵は「SSH 鍵管理」メニューで管理。
  let extraKeys: StoredKey[] = [];
  try {
    extraKeys = loadKeyStore().keys;
  } catch (e) {
    console.error(
      yellow(`[cloopy] 警告: ${e instanceof Error ? e.message : e}`),
    );
    console.error(
      yellow("[cloopy] 追加鍵を読み込めないため、自動生成鍵のみで構成します"),
    );
  }
  rebuildAuthorizedKeys(extraKeys);
  if (extraKeys.length > 0) {
    console.log(
      dim(
        `[cloopy] 追加鍵 ${extraKeys.length} 件を authorized_keys に含めました`,
      ),
    );
  }
  console.log("");

  // --------------------------------------------------------------------------
  // 2. .env 設定 (自動 + 対話)
  // --------------------------------------------------------------------------
  console.log(bold("--- ステップ 2: 環境設定 ---"));
  const envPath = ensureEnvFile(projectRoot);

  // 自動設定 (マーカーセクションに配置)
  // 旧バージョンの .env は id_ed25519.pub を直接指すが、setEnvVar が
  // その場で束ファイルパスへ上書きするため再 setup だけで移行が完了する
  setEnvVar(envPath, "CLOOPY_PUBKEY_PATH", authorizedKeysPath(), true);

  if (Deno.build.os !== "windows") {
    const uid = new Deno.Command("id", { args: ["-u"], stdout: "piped" });
    const gid = new Deno.Command("id", { args: ["-g"], stdout: "piped" });
    const [uidResult, gidResult] = await Promise.all([
      uid.output(),
      gid.output(),
    ]);
    const uidStr = new TextDecoder().decode(uidResult.stdout).trim();
    const gidStr = new TextDecoder().decode(gidResult.stdout).trim();
    setEnvVar(envPath, "CLOOPY_USER_UID", uidStr, true);
    setEnvVar(envPath, "CLOOPY_USER_GID", gidStr, true);
  }

  console.log("");

  // 対話設定 — デフォルト値は .env の保存値を優先する（Deno.env はシェルで
  // export された場合のフォールバック。.env は docker compose が読むだけで
  // CLI プロセスの環境変数には載らない）
  const savedEnv = readEnvFile(projectRoot);
  const currentInstance = savedEnv.get("CLOOPY_INSTANCE_NAME") ??
    Deno.env.get("CLOOPY_INSTANCE_NAME") ??
    DEFAULT_INSTANCE_NAME;
  // リモート接続エントリと SSH Host 名前空間を共有するため、衝突する名前は
  // 拒否する (許すと injectSshConfig がリモート向けブロックを localhost で
  // 上書きし、そのエントリが黙って壊れる)
  let remoteNames: string[] = [];
  try {
    remoteNames = loadRemoteStore().remotes.map((r) => r.name);
  } catch {
    // store 破損時は衝突チェックを諦める (破損の警告はリモート接続メニュー側)
  }
  const instanceInput = await Input.prompt({
    message: "インスタンス名 (SSH ホスト名・ボリュームプレフィックス)",
    default: currentInstance,
    validate: (v) => {
      if (!/^[a-zA-Z][a-zA-Z0-9_-]*$/.test(v)) {
        return "英字で始まり、英数字・ハイフン・アンダースコアのみ使用できます";
      }
      if (remoteNames.includes(v)) {
        return `"${v}" はリモート接続エントリで使用中です (リモート接続メニューで削除してから使用できます)`;
      }
      return true;
    },
  });
  if (instanceInput !== currentInstance) {
    setEnvVar(envPath, "CLOOPY_INSTANCE_NAME", instanceInput);
  }

  const currentPort = savedEnv.get("CLOOPY_SSH_PORT") ??
    Deno.env.get("CLOOPY_SSH_PORT") ?? DEFAULT_SSH_PORT;
  const portInput = await Input.prompt({
    message: "SSH ポート",
    default: currentPort,
    validate: (v) => {
      const n = Number(v);
      if (!Number.isInteger(n) || n < 1 || n > 65535) {
        return "1〜65535 の整数を入力してください";
      }
      return true;
    },
  });
  if (portInput !== currentPort) {
    setEnvVar(envPath, "CLOOPY_SSH_PORT", portInput);
  }

  // SSH 公開範囲。空 = 全インターフェース (Docker 既定 = 従来挙動)、
  // LOCAL_BIND = localhost のみ。既存 .env で未設定なら従来どおり公開されて
  // きたので「はい」を既定に（無断で挙動を変えない）。新規は安全側の
  // 「いいえ」を既定にする。手編集されたカスタム bind (特定 IP 等) は
  // 二択質問で潰さず、そのまま維持する。
  const currentBind = savedEnv.get("CLOOPY_SSH_BIND") ?? "";
  let lanInput = true;
  if (currentBind !== "" && currentBind !== LOCAL_BIND) {
    console.log(
      dim(
        `[cloopy] SSH 公開範囲: カスタム設定 CLOOPY_SSH_BIND=${currentBind} を維持します`,
      ),
    );
  } else {
    lanInput = await Confirm.prompt({
      message:
        "SSH を LAN の他のマシンに公開しますか？ (いいえ = このマシンからのみ接続可)",
      default: envExisted ? currentBind === "" : false,
    });
    const newBind = lanInput ? "" : LOCAL_BIND;
    if (newBind !== currentBind) {
      setEnvVar(envPath, "CLOOPY_SSH_BIND", newBind);
    }
  }

  const currentTz = savedEnv.get("CLOOPY_TIMEZONE") ??
    Deno.env.get("CLOOPY_TIMEZONE") ?? DEFAULT_TIMEZONE;
  const tzInput = await Input.prompt({
    message: "タイムゾーン",
    default: currentTz,
    validate: (v) => {
      try {
        Intl.DateTimeFormat(undefined, { timeZone: v });
        return true;
      } catch {
        return "無効なタイムゾーンです (例: Asia/Tokyo, UTC)";
      }
    },
  });
  if (tzInput !== currentTz) setEnvVar(envPath, "CLOOPY_TIMEZONE", tzInput);

  const currentWs = savedEnv.get("CLOOPY_HOST_WORKSPACE") ??
    Deno.env.get("CLOOPY_HOST_WORKSPACE") ?? DEFAULT_WORKSPACE;
  const wsInput = await Input.prompt({
    message: "ワークスペースパス",
    default: currentWs,
    validate: validateWorkspacePath,
  });
  if (wsInput !== currentWs) {
    setEnvVar(envPath, "CLOOPY_HOST_WORKSPACE", wsInput);
  }

  const useVolume = await Confirm.prompt({
    message:
      "ワークスペースに Docker ボリュームを使用しますか？ (Windows 推奨)",
    default: false,
  });
  setEnvVar(
    envPath,
    "CLOOPY_WORKSPACE_VOLUME",
    useVolume ? "true" : "false",
    true,
  );

  // docker-compose.local.yml を生成
  generateLocalCompose(projectRoot, { workspaceVolume: useVolume });
  console.log("");

  // --------------------------------------------------------------------------
  // 3. SSH 設定
  // --------------------------------------------------------------------------
  console.log(bold("--- ステップ 3: SSH 設定 ---"));
  injectSshConfig(portInput, instanceInput);
  console.log("");

  // --------------------------------------------------------------------------
  // 4. 起動
  // --------------------------------------------------------------------------
  console.log(bold("--- ステップ 4: 起動 ---"));
  console.log("[cloopy] コンテナを起動中...");
  // イメージ未存在の場合は docker compose が自動でビルドする
  const code = await compose(projectRoot, [...COMPOSE_UP_ARGS]);
  if (code !== 0) {
    console.error("[cloopy] エラー: コンテナの起動に失敗しました");
    console.error(
      "[cloopy] 設定は保存済みです。上のログで原因を解消してから ./manage.sh を再実行してください",
    );
    Deno.exit(1);
  }

  await refreshKnownHosts(portInput);
  await checkBootstrapStatus(projectRoot);
  console.log("");

  // --------------------------------------------------------------------------
  // 完了
  // --------------------------------------------------------------------------
  console.log(bold(green("  cloopy の準備ができました！")));
  console.log("");
  console.log(`  SSH:      ${cyan(`ssh ${instanceInput}`)}`);
  console.log(
    `  VS Code:  ${
      cyan(
        `code --remote ssh-remote+${instanceInput} /home/developer/workspace`,
      )
    }`,
  );
  if (lanInput) {
    console.log(
      dim(
        `  他マシンから: 接続元の cloopy メニュー「リモート接続」で\n` +
          `  このマシンの IP とポート ${portInput} を登録すると ssh 一発で繋がります`,
      ),
    );
  }
  console.log("");
}
