import { resolve } from "@std/path";

/** Get the home directory */
function homeDir(): string {
  if (Deno.build.os === "windows") {
    return Deno.env.get("USERPROFILE") ?? "C:\\Users\\Default";
  }
  return Deno.env.get("HOME") ?? "/home";
}

/** Get the cloopy SSH directory (~/.ssh/cloopy/) */
export function sshDir(): string {
  return resolve(homeDir(), ".ssh", "cloopy");
}

/** Get the SSH key path */
export function keyPath(): string {
  return resolve(sshDir(), "id_ed25519");
}

/** Get the public key path */
export function pubKeyPath(): string {
  return resolve(sshDir(), "id_ed25519.pub");
}

/** Get the cloopy SSH config path (~/.ssh/cloopy/config) */
export function sshConfigPath(): string {
  return resolve(sshDir(), "config");
}

/** Get the cloopy known_hosts path (~/.ssh/cloopy/known_hosts) */
export function knownHostsPath(): string {
  return resolve(sshDir(), "known_hosts");
}

/** Get the main SSH config path (~/.ssh/config) */
export function mainSshConfigPath(): string {
  return resolve(homeDir(), ".ssh", "config");
}

/**
 * Generate SSH key pair if not already present.
 * Returns true if a new key was generated.
 */
export async function ensureKeyPair(): Promise<boolean> {
  const key = keyPath();

  try {
    Deno.statSync(key);
    console.log("[cloopy] SSH key already exists, skipping");
    return false;
  } catch {
    // Key doesn't exist, generate
  }

  const dir = sshDir();
  Deno.mkdirSync(dir, { recursive: true });

  console.log("[cloopy] Generating SSH key...");
  const cmd = new Deno.Command("ssh-keygen", {
    args: ["-t", "ed25519", "-f", key, "-N", "", "-C", "cloopy"],
    stdout: "inherit",
    stderr: "inherit",
  });
  const { code } = await cmd.output();
  if (code !== 0) {
    throw new Error("ssh-keygen failed");
  }

  return true;
}

/**
 * Write the cloopy SSH config file and ensure Include in main config.
 */
export function injectSshConfig(port: string): void {
  const dir = sshDir();
  Deno.mkdirSync(dir, { recursive: true });

  // SSH config needs forward slashes even on Windows
  const toSshPath = (p: string) => p.replaceAll("\\", "/");

  // Write cloopy-specific config (always overwrite to keep in sync)
  const configContent = `# cloopy - Claude Code sandbox
# Auto-generated by cloopy setup. Edit freely.
Host cloopy
    HostName localhost
    Port ${port}
    User developer
    IdentityFile ${toSshPath(keyPath())}
    StrictHostKeyChecking accept-new
    UserKnownHostsFile ${toSshPath(knownHostsPath())}
`;
  Deno.writeTextFileSync(sshConfigPath(), configContent);

  // Ensure Include directive in main SSH config
  const mainConfig = mainSshConfigPath();
  const mainDir = resolve(homeDir(), ".ssh");
  Deno.mkdirSync(mainDir, { recursive: true });

  let mainContent: string;
  try {
    mainContent = Deno.readTextFileSync(mainConfig);
  } catch {
    mainContent = "";
  }

  const includeLine = `Include ${toSshPath(sshConfigPath())}`;

  if (!mainContent.includes(includeLine)) {
    console.log("[cloopy] Adding Include directive to SSH config...");
    const newContent = `# --- cloopy ---\n${includeLine}\n\n${mainContent}`;
    Deno.writeTextFileSync(mainConfig, newContent);
  } else {
    console.log("[cloopy] SSH config Include already present, skipping");
  }
}

/**
 * Fetch the current host key via ssh-keyscan and overwrite known_hosts.
 * Call this after container start/rebuild so tools never see a key-changed prompt.
 */
export async function refreshKnownHosts(port: string): Promise<void> {
  console.log("[cloopy] known_hosts を更新中...");
  const cmd = new Deno.Command("ssh-keyscan", {
    args: ["-p", port, "-H", "localhost"],
    stdout: "piped",
    stderr: "null",
  });
  const { code, stdout } = await cmd.output();
  if (code !== 0) {
    console.error("[cloopy] ssh-keyscan に失敗しました");
    return;
  }
  const keys = new TextDecoder().decode(stdout).trim();
  if (!keys) {
    console.error("[cloopy] ssh-keyscan: キーが取得できませんでした");
    return;
  }
  Deno.mkdirSync(sshDir(), { recursive: true });
  Deno.writeTextFileSync(knownHostsPath(), keys + "\n");
  console.log("[cloopy] known_hosts を更新しました");
}
